# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [1]:
import numpy as np

In [6]:
def create_matrix(n):
  """
  In this function you should create matrix in order of n*n with random numbers 
  in the [n, n+100) interval.

  see the bellow link:
    https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

  Arguments:
    inputs:
      n: an integer describing the order of the matrix
    outputs:
      created matrix  
  """
  matrix = np.random.randint(n, n+100, size=(n,n))
  return matrix

array([[65, 50, 76, 35, 79],
       [89, 64, 80, 50, 81],
       [26, 17, 73, 42, 47],
       [44, 28, 32, 87, 95],
       [89, 83, 83, 39, 65]])

In [32]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
n = int(input())
matrix = create_matrix(n)
print(matrix)

[[ 82  75  93 103  38  96]
 [ 19  80  73  88  17  48]
 [ 87   6  76   6  96 100]
 [ 26  93  49  54  64  42]
 [ 10  73  70   8  69  18]
 [ 69  18 103  32  11   8]]


In [8]:
def count_digits(matrix):
  """
  In this function you should implement a routine to count the digits in the given matrix.

  Arguments:
    inputs:
      matrix: input matrix
    outputs:
      digits: a dictionary containing digits as its keys and the counted numbers as its value
  """
  digits = {}
  for row in matrix:
    for num in row:
      s = str(num)
      for digit in s:
        if digit not in digits:
          digits[digit] = 1
        else:
          digits[digit] += 1

  return digits


In [12]:
"""
In this cell call the implemented function and print the result
"""

result = count_digits(matrix)
print(result)

{'5': 10, '1': 6, '4': 8, '8': 5, '7': 4, '0': 4, '2': 3, '3': 5, '6': 1, '9': 5}


## Part B

In [33]:
def find_next_cell(matrix, curr_cell, dir_ind, directions):
  next_cell = None
  if directions[dir_ind] == 'right':
    new_col = curr_cell[1] + 1
    if new_col < matrix.shape[1] and new_col > -1:
      next_cell = (curr_cell[0], new_col)
  elif directions[dir_ind] == 'down':
    new_row = curr_cell[0] + 1
    if new_row < matrix.shape[0] and new_row > -1:
      next_cell = (new_row, curr_cell[1])
  elif directions[dir_ind] == 'diagonal down':
    next_row = curr_cell[0] + 1
    next_col = curr_cell[1] - 1
    if next_row < matrix.shape[0] and next_col < matrix.shape[1] and next_row > -1 and next_col > -1:
      next_cell = (next_row, next_col)
  else:
    next_row = curr_cell[0] - 1
    next_col = curr_cell[1] + 1
    if next_row < matrix.shape[0] and next_col < matrix.shape[1] and next_row > -1 and next_col > -1:
      next_cell = (next_row, next_col)
  return next_cell





def traverse_matrix(matrix):
  """
  Traverse the input matrix in the given manner then print result

  Arguments:
    inputs:
      matrix: input matrix
    outputs
  """
  directions = ['right', 'diagonal down', 'down', 'diagonal up']
  dir_ind = 0
  leng = matrix.size
  curr_cell = (0,0)
  finish = 1
  flag = 0
  print(matrix[curr_cell[0], curr_cell[1]], end=', ')
  while(finish != leng):
    next_cell = find_next_cell(matrix, curr_cell, dir_ind, directions)
    if next_cell is not None:
      print(matrix[next_cell[0], next_cell[1]], end=', ')
      curr_cell = next_cell
      finish += 1
      if dir_ind in [0,2]:
        dir_ind = (dir_ind + 1) % 4
    else:
      if curr_cell[0] == matrix.shape[0] - 1 and not flag:
        directions[1] = 'diagonal up'
        directions[3] = 'diagonal down'
        dir_ind = 0
        flag = 1
      elif curr_cell[1] == matrix.shape[1] - 1 and not flag:
        directions[0] = 'down'
        directions[2] = 'right'
        dir_ind = 0
        flag = 1
      else:
        dir_ind = (dir_ind + 1) % 4


      

  

In [34]:
print(matrix)
traverse_matrix(matrix)
#print output

[[ 82  75  93 103  38  96]
 [ 19  80  73  88  17  48]
 [ 87   6  76   6  96 100]
 [ 26  93  49  54  64  42]
 [ 10  73  70   8  69  18]
 [ 69  18 103  32  11   8]]
82, 75, 19, 87, 80, 93, 103, 73, 6, 26, 10, 93, 76, 88, 38, 96, 17, 6, 49, 73, 69, 18, 70, 54, 96, 48, 100, 64, 8, 103, 32, 69, 42, 18, 11, 8, 