# Q4

## Part A

In [1]:
import numpy as np

In [11]:
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""

matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix2 = np.array([[1], [-1], [1]])
m1_transpose = np.transpose(matrix1)
multiplied = np.dot(m1_transpose, matrix1)
inv_multiplied = np.linalg.inv(multiplied)
middle = np.dot(np.dot(inv_multiplied, m1_transpose), matrix2)
final = np.add(middle, matrix1)
print(final)

[[0.796875 1.796875 2.796875]
 [4.       5.       6.      ]
 [7.203125 8.203125 9.203125]]


## Part B

In [13]:
def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """

  res = np.zeros([3,3], dtype=int)
  for i in range(3):
    for j in range(3):
      res[i, j] = np.sum(np.multiply(A, B[i:i+3, j:j+3]))

  return res

In [15]:
B = np.array([
  [1,1,1,1,1],[1,2,2,2,1],[1,2,2,2,1],[1,2,2,2,1],[1,1,1,1,1]
])
A = np.array([
  [1,1,1], [1, -9, 1], [1,1,1]
])
print(window_sliding(A, B))

[[-7 -5 -7]
 [-5 -2 -5]
 [-7 -5 -7]]
